### ISSUE TITLE
"Bad state: No element Map" error After login

### ISSUE THREAD

**Issue by pppurle** [fridolinf/supabase_example#1]
Hi. 
I'm very new flutter and supabase. 
I found your app and I really interested so I cloned.
but I'm having problem. May I ask question? 

I made tables and tryed to login. 
Seems like I loggined succesfully 
but A loading icon show up center and app stoped.
Then I got this error at Homecontroller.dart
`Bad state: No element Map<String, dynamic> user = (res).first as Map<String, dynamic>;	`

```
List<dynamic> res = await client
        .from("users")
        .select("id")
        .match({"uid": client.auth.currentUser!.id});
  Map<String, dynamic> user = (res).first as Map<String, dynamic>;

```	
	
I read README file. but I'm not sure tables schema.
Could you teach me solution and I would like to make sure Table shema that users and notes column name ?

**Comment by fridolinf** [comment]
Hello @pppurle ,
I've added the DB schema in the readme. Just check it again. 
I hope it can help solve the problem you encountered

**Comment by pppurle** [comment]
Hi. @fridolinf 
Thank you very much for updating README.
I can successfully make talbes anf I can register user data.
After I registration. I can see the success toast pop up.
then I can jump login page.
Than you!

But I have anoter probkem.
I tried to login using this registered infomation. 
I got this error 

AuthException(message Email not fonfirmed. statusCode 400)

When I look at supabase page. I can see the user was regsitered.

I thoguht I might did code change this project. So I re-cloned your project. but This clean project also happen same error.

I did only below command for solving red colored mark error

dart fix --dry-run
dart fix --apply
erase widget_test.dart 

Could you help me more please?
![auth error ](https://github.com/fridolinf/supabase_example/assets/149898767/1d289681-d013-40f0-8ddc-b5302379b3f1)

**Comment by fridolinf** [comment]
Try registering with the correct email first, as I remember you have to confirm the email first before logging in

**Comment by pppurle** [comment]
It workded! 
I see! I don't see any column for confirm info so I didn't check Email! 
Thank you very much for all of your help.

**Comment by fridolinf** [comment]
sure mate no worries
